- hosts: all
  become: yes
  tasks:
  - name: Deps
    import_role:
      name: common
      tasks_from: deps
- hosts: masters:servermasters
  become: yes
  tasks:
  - name: Deps
    import_role:
      name: masters
      tasks_from: deps
